#!/usr/bin/env python3
"""
Build ebook from knowledge markdown files.
Uses existing HTML files (auto-generated by VS Code extension) to create EPUB.

Usage: python build_ebook.py
Output: ebook/python-fundamentals.epub
"""

import os
from pathlib import Path
try:
    import markdown
    from ebooklib import epub
    from bs4 import BeautifulSoup
except ImportError:
    print("⚠️  Missing dependencies. Installing...")
    import subprocess
    subprocess.check_call(["pip", "install", "markdown", "ebooklib", "beautifulsoup4"])
    import markdown
    from ebooklib import epub
    from bs4 import BeautifulSoup


# Configuration
KNOWLEDGE_DIR = Path(__file__).parent
HTML_DIR = KNOWLEDGE_DIR / "html"
EBOOK_DIR = KNOWLEDGE_DIR / "ebook"
OUTPUT_FILE = EBOOK_DIR / "python-fundamentals.epub"

# Chapter order (matches learning sequence)
# Uses existing HTML files generated by your VS Code extension from html/ folder
CHAPTERS = [
    ("lists", "Lists"),
    ("tuples", "Tuples"),
    ("dictionaries", "Dictionaries"),
    ("sets", "Sets"),
    ("mutability", "Mutability"),
    ("oop", "Object-Oriented Programming"),
    ("functions", "Functions"),
    ("error-handling", "Error Handling"),
    ("generators", "Generators & Iterators"),
    ("imports-modules", "Imports & Modules"),
]


def load_existing_html(html_file):
    """Load existing HTML file generated by VS Code extension."""
    with open(html_file, 'r', encoding='utf-8') as f:
        html_content = f.read()

    # Extract body content (remove HTML/HEAD tags)
    soup = BeautifulSoup(html_content, 'html.parser')
    body = soup.find('body')
    return str(body) if body else html_content


def create_epub():
    """Create EPUB ebook from markdown files."""
    print("📚 Building Python Fundamentals ebook...")

    # Create book
    book = epub.EpubBook()
    book.set_identifier('python-fundamentals-andrea-bruni')
    book.set_title('Python Fundamentals')
    book.set_language('en')
    book.add_author('Andrea Bruni')

    # Add metadata
    book.add_metadata('DC', 'description',
                      'Comprehensive Python fundamentals guide covering data structures, OOP, and core concepts.')

    # CSS for styling
    css = '''
    @namespace epub "http://www.idpf.org/2007/ops";
    body {
        font-family: Georgia, serif;
        line-height: 1.6;
        padding: 20px;
    }
    h1 {
        color: #2c3e50;
        border-bottom: 3px solid #3498db;
        padding-bottom: 10px;
    }
    h2 {
        color: #34495e;
        margin-top: 30px;
    }
    code {
        background-color: #f4f4f4;
        padding: 2px 6px;
        border-radius: 3px;
        font-family: 'Monaco', 'Courier New', monospace;
        font-size: 0.9em;
    }
    pre {
        background-color: #f8f8f8;
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 15px;
        overflow-x: auto;
    }
    pre code {
        background-color: transparent;
        padding: 0;
    }
    table {
        border-collapse: collapse;
        width: 100%;
        margin: 20px 0;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }
    th {
        background-color: #3498db;
        color: white;
    }
    blockquote {
        border-left: 4px solid #3498db;
        padding-left: 20px;
        margin-left: 0;
        color: #555;
    }
    '''

    nav_css = epub.EpubItem(
        uid="style_nav",
        file_name="style/nav.css",
        media_type="text/css",
        content=css
    )
    book.add_item(nav_css)

    # Process chapters
    chapters = []
    toc = []
    spine = ['nav']

    for idx, (stem, title) in enumerate(CHAPTERS, 1):
        # Check for existing HTML file in html/ folder (generated by VS Code extension)
        html_file = HTML_DIR / f"{stem}.html"
        md_file = KNOWLEDGE_DIR / f"{stem}.md"

        if html_file.exists():
            print(f"  📄 Using existing HTML: html/{stem}.html")
            html_content = load_existing_html(html_file)
        elif md_file.exists():
            print(f"  📄 Converting from MD: {stem}.md")
            html_content = markdown.markdown(
                md_file.read_text(encoding='utf-8'),
                extensions=['fenced_code', 'tables', 'codehilite', 'toc']
            )
        else:
            print(f"⚠️  Skipping {stem} (no HTML or MD found)")
            continue

        # Create EPUB chapter
        chapter = epub.EpubHtml(
            title=title,
            file_name=f'chapter_{idx}.xhtml',
            lang='en'
        )
        chapter.content = f'<h1>{title}</h1>{html_content}'
        chapter.add_item(nav_css)

        book.add_item(chapter)
        chapters.append(chapter)
        toc.append(epub.Link(f'chapter_{idx}.xhtml', title, f'chapter_{idx}'))
        spine.append(chapter)

    # Add intro chapter
    intro = epub.EpubHtml(title='Introduction', file_name='intro.xhtml', lang='en')
    intro.content = '''
    <h1>Python Fundamentals</h1>
    <p><strong>Author:</strong> Andrea Bruni</p>
    <p><strong>Last updated:</strong> May 2026</p>
    <hr>
    <p>This ebook contains comprehensive notes on Python fundamentals, created during an 8-week learning journey from marketing to AI engineering.</p>
    <p><strong>Topics covered:</strong></p>
    <ul>
        <li>Data structures (lists, tuples, dictionaries, sets)</li>
        <li>Mutability and memory management</li>
        <li>Object-oriented programming</li>
        <li>Best practices and common pitfalls</li>
    </ul>
    <p>Each chapter includes practical examples, comparisons with JavaScript, and real-world applications.</p>
    '''
    intro.add_item(nav_css)
    book.add_item(intro)

    # Configure book structure
    book.toc = (
        epub.Link('intro.xhtml', 'Introduction', 'intro'),
        (epub.Section('Core Concepts'), toc)
    )
    book.spine = ['nav', intro] + spine
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    # Write EPUB
    epub.write_epub(OUTPUT_FILE, book, {})
    print(f"\n✅ Ebook created: {OUTPUT_FILE}")
    print(f"📱 Transfer to iPad via AirDrop and open with Apple Books\n")

    # Summary
    print(f"📊 Summary:")
    print(f"   - Chapters: {len(chapters)}")
    print(f"   - Source HTML files: {len(list(HTML_DIR.glob('*.html')))}")
    print(f"   - EPUB size: {OUTPUT_FILE.stat().st_size / 1024:.1f} KB")


if __name__ == '__main__':
    # Ensure ebook directory exists
    EBOOK_DIR.mkdir(exist_ok=True)

    # Build ebook
    create_epub()
